name:                write-you-a-lisp
version:             0.1.0.0
github:              "micahcantor/write-you-a-lisp"
license:             MIT
author:              "Micah Cantor"
maintainer:          "hello@micahcantor.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/micahcantor/writing-a-lisp#readme>

dependencies:
- relude
- base

library:
  source-dirs: src
  default-extensions: OverloadedStrings, NoImplicitPrelude, NamedFieldPuns
  dependencies:
  - text
  - parsec
  - containers
  - mtl

executables:
  writing-a-lisp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions: OverloadedStrings, NoImplicitPrelude
    dependencies:
    - write-you-a-lisp
    - haskeline

tests:
  writing-a-lisp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - write-you-a-lisp
